/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TwoOwnerAccount } from "./TwoOwnerAccount";
export type { TwoOwnerAccountFactory } from "./TwoOwnerAccountFactory";
