/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TwoOwnerAccount__factory } from "./TwoOwnerAccount__factory";
export { TwoOwnerAccountFactory__factory } from "./TwoOwnerAccountFactory__factory";
